---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-v1
spec:
  selector:
    matchLabels:
      app: helloapp-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: helloapp-v1
    spec:
      containers:
      - name: helloapp-v1
        image: hw0008acr.azurecr.io/samples/helloapp
        ports:
        - containerPort: 80